### ISSUE TITLE
Длинные слова

### ISSUE THREAD

**Issue by shevdi** [Zarwlar/Site_1#1]
Если ввести длинное имя или фамилию, то оно вылазит за края.

**Comment by Zarwlar** [comment]
Исправил)

**Comment by shevdi** [comment]
Не знаю только как на твоем экране, но теперь у меня сверху фамилия обрезается из-за overflow. Можно еще разбивать слова с переносом слова на следующую строку.

**Comment by Zarwlar** [comment]
Заменил overflow на word-wrap у surname
