### ISSUE TITLE
глобальные стили

### ISSUE THREAD

**Issue by shevdi** [Zarwlar/Site_1#5]
Некоторые стили, например, шрифты, которые цепляются на на <html>, или глобальные переменные лучше вынести в отдельный файл.

**Comment by Zarwlar** [comment]
Если честно, я не понял, что нужно сделать)

**Comment by shevdi** [comment]
Создается общий корневой для всех компонент .styl файл, где можно указать, например, для html
font-family: sans-serif
font-size: 16px

**Comment by Zarwlar** [comment]
Окей, добавил
