### ISSUE TITLE
Ширина прогресс-баров

### ISSUE THREAD

**Issue by NikitaRzm** [Zarwlar/Site_1#8]
[Здесь](https://github.com/Zarwlar/Site_1/blob/master/src/blocks/software/software.pug#L7) заполненность прогресс-баров указана в em. Гораздо естественнее и проще использовать в таких случаях проценты, т.к. это естественнее. Если прогресс-бар заполнен на 45%, то мы миксину так и скажем в аргументе: 45%.

**Comment by Zarwlar** [comment]
Em в мастер ветке, а в ветке рефакторинга я исправил на проценты)
